"""Unofficial Python client for Korea Expressway Corporation OpenAPIs."""

from .client import KexClient
from .codes import (
    CarType,
    CongestionLevel,
    Direction,
    DiscountType,
    IOType,
    RoadOperator,
    TCSType,
    TimeUnit,
)
from .exceptions import (
    KexAuthError,
    KexBadRequestError,
    KexConfigError,
    KexConnectionError,
    KexError,
    KexInvalidParameterError,
    KexMissingParameterError,
    KexNetworkError,
    KexNotFoundError,
    KexParseError,
    KexQuotaExceededError,
    KexServerError,
    KexServiceUnavailableError,
    KexTimeoutError,
)
from .models import (
    FoodPrice,
    Incident,
    Page,
    RestArea,
    Route,
    TollFee,
    Tollgate,
    TrafficByIc,
    TrafficFlow,
)

__all__ = [
    "CarType",
    "CongestionLevel",
    "Direction",
    "DiscountType",
    "FoodPrice",
    "IOType",
    "Incident",
    "KexAuthError",
    "KexBadRequestError",
    "KexClient",
    "KexConfigError",
    "KexConnectionError",
    "KexError",
    "KexInvalidParameterError",
    "KexMissingParameterError",
    "KexNetworkError",
    "KexNotFoundError",
    "KexParseError",
    "KexQuotaExceededError",
    "KexServerError",
    "KexServiceUnavailableError",
    "KexTimeoutError",
    "Page",
    "RestArea",
    "RoadOperator",
    "Route",
    "TCSType",
    "TimeUnit",
    "TollFee",
    "Tollgate",
    "TrafficByIc",
    "TrafficFlow",
]
