"""한국도로공사 OpenAPI 비공식 Python 클라이언트."""

from kraddr.base import Address, PlaceCoordinate

from .client import KexClient
from .codes import (
    CarType,
    CongestionLevel,
    CoordinateSystem,
    Direction,
    DiscountType,
    IOType,
    KexCode,
    RoadOperator,
    TCSType,
    TimeUnit,
)
from .exceptions import (
    KexAuthError,
    KexBadRequestError,
    KexConfigError,
    KexConnectionError,
    KexError,
    KexInvalidParameterError,
    KexMissingParameterError,
    KexNetworkError,
    KexNotFoundError,
    KexParseError,
    KexQuotaExceededError,
    KexServerError,
    KexServiceUnavailableError,
    KexTimeoutError,
)
from .models import (
    FoodPrice,
    Incident,
    KexModel,
    Page,
    RawCoordinate,
    RestArea,
    RestAreaFuelPrice,
    RestAreaRouteFacility,
    RestAreaWeather,
    Route,
    TollFee,
    Tollgate,
    TrafficByIc,
    TrafficFlow,
)

__all__ = [
    "Address",
    "CarType",
    "CongestionLevel",
    "CoordinateSystem",
    "Direction",
    "DiscountType",
    "FoodPrice",
    "IOType",
    "Incident",
    "KexCode",
    "KexAuthError",
    "KexBadRequestError",
    "KexClient",
    "KexConfigError",
    "KexConnectionError",
    "KexError",
    "KexInvalidParameterError",
    "KexMissingParameterError",
    "KexModel",
    "KexNetworkError",
    "KexNotFoundError",
    "KexParseError",
    "KexQuotaExceededError",
    "KexServerError",
    "KexServiceUnavailableError",
    "KexTimeoutError",
    "Page",
    "PlaceCoordinate",
    "RawCoordinate",
    "RestArea",
    "RestAreaFuelPrice",
    "RestAreaRouteFacility",
    "RestAreaWeather",
    "RoadOperator",
    "Route",
    "TCSType",
    "TimeUnit",
    "TollFee",
    "Tollgate",
    "TrafficByIc",
    "TrafficFlow",
]
